// swift-tools-version: 5.9
import PackageDescription

func webRTCAec3Excludes() -> [String] {
    [
        "third_party/webrtc/AUTHORS",
        "third_party/webrtc/LICENSE",
        "third_party/webrtc/PATENTS",
        "third_party/abseil-cpp/AUTHORS",
        "third_party/abseil-cpp/LICENSE",
        "third_party/jsoncpp/AUTHORS",
        "third_party/jsoncpp/LICENSE",
        "third_party/PROVENANCE.md",
    ]
}

func webRTCAec3Sources() -> [String] {
    [
        "WebRTCAec3Bridge.cc",
        "third_party/webrtc/api/audio/audio_frame.cc",
        "third_party/webrtc/api/audio/channel_layout.cc",
        "third_party/webrtc/api/audio/echo_canceller3_config.cc",
        "third_party/webrtc/api/audio/echo_canceller3_config_json.cc",
        "third_party/webrtc/api/audio/echo_canceller3_factory.cc",
        "third_party/webrtc/modules/audio_processing/aec3/adaptive_fir_filter.cc",
        "third_party/webrtc/modules/audio_processing/aec3/aec3_common.cc",
        "third_party/webrtc/modules/audio_processing/aec3/aec3_fft.cc",
        "third_party/webrtc/modules/audio_processing/aec3/aec_state.cc",
        "third_party/webrtc/modules/audio_processing/aec3/api_call_jitter_metrics.cc",
        "third_party/webrtc/modules/audio_processing/aec3/block_delay_buffer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/block_framer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/block_processor.cc",
        "third_party/webrtc/modules/audio_processing/aec3/block_processor_metrics.cc",
        "third_party/webrtc/modules/audio_processing/aec3/clockdrift_detector.cc",
        "third_party/webrtc/modules/audio_processing/aec3/comfort_noise_generator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/decimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/downsampled_render_buffer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/echo_audibility.cc",
        "third_party/webrtc/modules/audio_processing/aec3/echo_canceller3.cc",
        "third_party/webrtc/modules/audio_processing/aec3/echo_path_delay_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/echo_path_variability.cc",
        "third_party/webrtc/modules/audio_processing/aec3/echo_remover.cc",
        "third_party/webrtc/modules/audio_processing/aec3/echo_remover_metrics.cc",
        "third_party/webrtc/modules/audio_processing/aec3/erl_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/erle_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/fft_buffer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/filter_analyzer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/frame_blocker.cc",
        "third_party/webrtc/modules/audio_processing/aec3/fullband_erle_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/main_filter_update_gain.cc",
        "third_party/webrtc/modules/audio_processing/aec3/matched_filter.cc",
        "third_party/webrtc/modules/audio_processing/aec3/matched_filter_lag_aggregator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/matrix_buffer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/moving_average.cc",
        "third_party/webrtc/modules/audio_processing/aec3/render_buffer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/render_delay_buffer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/render_delay_controller.cc",
        "third_party/webrtc/modules/audio_processing/aec3/render_delay_controller_metrics.cc",
        "third_party/webrtc/modules/audio_processing/aec3/render_reverb_model.cc",
        "third_party/webrtc/modules/audio_processing/aec3/render_signal_analyzer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/residual_echo_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/reverb_decay_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/reverb_frequency_response.cc",
        "third_party/webrtc/modules/audio_processing/aec3/reverb_model.cc",
        "third_party/webrtc/modules/audio_processing/aec3/reverb_model_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/shadow_filter_update_gain.cc",
        "third_party/webrtc/modules/audio_processing/aec3/signal_dependent_erle_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/stationarity_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/subband_erle_estimator.cc",
        "third_party/webrtc/modules/audio_processing/aec3/subtractor.cc",
        "third_party/webrtc/modules/audio_processing/aec3/subtractor_output.cc",
        "third_party/webrtc/modules/audio_processing/aec3/subtractor_output_analyzer.cc",
        "third_party/webrtc/modules/audio_processing/aec3/suppression_filter.cc",
        "third_party/webrtc/modules/audio_processing/aec3/suppression_gain.cc",
        "third_party/webrtc/modules/audio_processing/aec3/vector_buffer.cc",
        "third_party/webrtc/modules/audio_processing/audio_buffer.cc",
        "third_party/webrtc/modules/audio_processing/high_pass_filter.cc",
        "third_party/webrtc/modules/audio_processing/logging/apm_data_dumper.cc",
        "third_party/webrtc/modules/audio_processing/splitting_filter.cc",
        "third_party/webrtc/modules/audio_processing/three_band_filter_bank.cc",
        "third_party/webrtc/modules/audio_processing/utility/cascaded_biquad_filter.cc",
        "third_party/webrtc/modules/audio_processing/utility/ooura_fft.cc",
        "third_party/webrtc/modules/audio_processing/utility/ooura_fft_neon.cc",
        "third_party/webrtc/common_audio/channel_buffer.cc",
        "third_party/webrtc/common_audio/audio_util.cc",
        "third_party/webrtc/common_audio/resampler/push_sinc_resampler.cc",
        "third_party/webrtc/common_audio/resampler/sinc_resampler.cc",
        "third_party/webrtc/common_audio/resampler/sinc_resampler_neon.cc",
        "third_party/webrtc/common_audio/signal_processing/splitting_filter.c",
        "third_party/webrtc/common_audio/sparse_fir_filter.cc",
        "third_party/webrtc/common_audio/wav_file.cc",
        "third_party/webrtc/common_audio/wav_header.cc",
        "third_party/abseil-cpp/absl/base/internal/raw_logging.cc",
        "third_party/abseil-cpp/absl/base/throw_delegate.cc",
        "third_party/abseil-cpp/absl/numeric/int128.cc",
        "third_party/abseil-cpp/absl/strings/ascii.cc",
        "third_party/abseil-cpp/absl/strings/charconv.cc",
        "third_party/abseil-cpp/absl/strings/escaping.cc",
        "third_party/abseil-cpp/absl/strings/internal/charconv_bigint.cc",
        "third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc",
        "third_party/abseil-cpp/absl/strings/internal/escaping.cc",
        "third_party/abseil-cpp/absl/strings/internal/memutil.cc",
        "third_party/abseil-cpp/absl/strings/internal/ostringstream.cc",
        "third_party/abseil-cpp/absl/strings/internal/stringify_sink.cc",
        "third_party/abseil-cpp/absl/strings/internal/utf8.cc",
        "third_party/abseil-cpp/absl/strings/match.cc",
        "third_party/abseil-cpp/absl/strings/numbers.cc",
        "third_party/abseil-cpp/absl/strings/str_cat.cc",
        "third_party/abseil-cpp/absl/strings/str_replace.cc",
        "third_party/abseil-cpp/absl/strings/str_split.cc",
        "third_party/abseil-cpp/absl/strings/substitute.cc",
        "third_party/jsoncpp/src/lib_json/json_reader.cpp",
        "third_party/jsoncpp/src/lib_json/json_value.cpp",
        "third_party/jsoncpp/src/lib_json/json_writer.cpp",
        "third_party/webrtc/rtc_base/checks.cc",
        "third_party/webrtc/rtc_base/critical_section.cc",
        "third_party/webrtc/rtc_base/logging.cc",
        "third_party/webrtc/rtc_base/memory/aligned_malloc.cc",
        "third_party/webrtc/rtc_base/platform_thread_types.cc",
        "third_party/webrtc/rtc_base/race_checker.cc",
        "third_party/webrtc/rtc_base/string_encode.cc",
        "third_party/webrtc/rtc_base/string_to_number.cc",
        "third_party/webrtc/rtc_base/string_utils.cc",
        "third_party/webrtc/rtc_base/strings/json.cc",
        "third_party/webrtc/rtc_base/strings/string_builder.cc",
        "third_party/webrtc/rtc_base/system/file_wrapper.cc",
        "third_party/webrtc/rtc_base/time_utils.cc",
        "third_party/webrtc/system_wrappers/source/cpu_features.cc",
        "third_party/webrtc/system_wrappers/source/field_trial.cc",
        "third_party/webrtc/system_wrappers/source/metrics.cc",
    ]
}

let package = Package(
    name: "MuesliNative",
    platforms: [
        .macOS("14.2"),
    ],
    products: [
        .library(name: "MuesliCore", targets: ["MuesliCore"]),
        .executable(name: "MuesliNativeApp", targets: ["MuesliNativeApp"]),
        .executable(name: "muesli-cli", targets: ["MuesliCLI"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.3.0"),
        .package(url: "https://github.com/FluidInference/FluidAudio.git", from: "0.12.2"),
        .package(url: "https://github.com/exPHAT/SwiftWhisper.git", branch: "master"),
        .package(url: "https://github.com/sparkle-project/Sparkle", from: "2.6.0"),
        .package(url: "https://github.com/TelemetryDeck/SwiftSDK", from: "2.0.0"),
    ],
    targets: [
        .target(
            name: "WebRTCAec3Bridge",
            dependencies: [],
            path: "Sources/WebRTCAec3Bridge",
            exclude: webRTCAec3Excludes(),
            sources: webRTCAec3Sources(),
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("third_party/webrtc"),
                .headerSearchPath("third_party/abseil-cpp"),
                .headerSearchPath("third_party/jsoncpp"),
                .headerSearchPath("third_party/jsoncpp/include"),
                .define("WEBRTC_MAC"),
                .define("WEBRTC_POSIX"),
                .define("WEBRTC_ARCH_ARM64"),
                .define("WEBRTC_HAS_NEON"),
                .define("WEBRTC_APM_DEBUG_DUMP", to: "0"),
            ],
            cxxSettings: [
                .headerSearchPath("third_party/webrtc"),
                .headerSearchPath("third_party/abseil-cpp"),
                .headerSearchPath("third_party/jsoncpp"),
                .headerSearchPath("third_party/jsoncpp/include"),
                .define("WEBRTC_MAC"),
                .define("WEBRTC_POSIX"),
                .define("WEBRTC_ARCH_ARM64"),
                .define("WEBRTC_HAS_NEON"),
                .define("WEBRTC_APM_DEBUG_DUMP", to: "0"),
            ]
        ),
        .target(
            name: "MuesliCore",
            dependencies: [],
            path: "Sources/MuesliCore",
            linkerSettings: [
                .linkedLibrary("sqlite3"),
            ]
        ),
        .executableTarget(
            name: "MuesliNativeApp",
            dependencies: [
                "MuesliCore",
                "WebRTCAec3Bridge",
                .product(name: "FluidAudio", package: "FluidAudio"),
                .product(name: "SwiftWhisper", package: "SwiftWhisper"),
                .product(name: "Sparkle", package: "Sparkle"),
                .product(name: "TelemetryDeck", package: "SwiftSDK"),
            ],
            path: "Sources/MuesliNativeApp",
            swiftSettings: [
                .unsafeFlags(["-parse-as-library"]),
            ],
            linkerSettings: [
                .linkedLibrary("sqlite3"),
            ]
        ),
        .executableTarget(
            name: "MuesliCLI",
            dependencies: [
                "MuesliCore",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Sources/MuesliCLI"
        ),
        .testTarget(
            name: "MuesliTests",
            dependencies: ["MuesliNativeApp", "MuesliCore", "MuesliCLI"],
            path: "Tests/MuesliTests",
            linkerSettings: [
                .linkedLibrary("sqlite3"),
            ]
        ),
    ],
    cxxLanguageStandard: .cxx17
)
